### PR TITLE
Adding OSGi manifest headers to thymeleaf core.

### PR DESCRIPTION
**Pull request by balazs-zsoldos**
As much as I see, there has been an issue since two years about this topic:

https://github.com/thymeleaf/thymeleaf/issues/32

I would like to ask you to add the changes to the pom.xml of thymeleaf!
We tested it and used it within Equinox and it worked for us. Some notes:

We used MVEL2 instead of OGNL. MVEL2 has a nice jar that also contains
OSGi MANIFEST entries. As MVEL2 could have been used pretty easily
(if we do not care that there are some syntax changes in the expressions), 
I made the OGNL and javassist packages optional in the MANIFEST.

We do not use Spring at all. Spring was designed to simplify the Java EE world
and it does a great job. However, the philosophy of Spring does not fit into the
OSGi KISS concept. Spring itself does not support OSGi anymore (although
OSGi is more widely supported from year to year). I think it is not important to handle
thymeleaf-core and thymeleaf-spring jars together concerning to OSGi.
As a first (and probably only one) step, it is enough to put OSGi MANIFEST
entries only into the thymeleaf-core.

### CODE REVIEW

**Comment by tangyong** [comment]
Again ask: Thymeleaf 2.1 has any plan to merge the pull request?

**Comment by ultraq** [comment]
I don't know much about OSGI (except that it annoys the hell out of me when developing the Eclipse plugin!), so I asked about this and the answer was that this probably won't get merged for 2.1 due to all the issues and workarounds described in #32.

**Comment by balazs-zsoldos** [comment]
> I don't know much about OSGI (except that it annoys the hell out of me when developing the Eclipse plugin!)

I am sorry to hear that. I hope that will change within the next years. OSGi is very hard to start with. There are strict rules and if any of the dependencies broke them, it makes developer feel pain. Rules like:
- No Class.forName in the code
- No ThreadContextClassLoader usage
- No configuration via static variables
- Use schemantic versioning strictly

Luckily the code of Thymeleaf meets all of the requirements.

In #32 there is no workaround. I read a couple of comments where developers were afraid of compatibility. Good news is that there is no such issue. By adding the OSGi MANIFEST header, any code will behave as it behaved outside of OSGi.

We really need an OSGified version of Thymeleaf as we would like to release the first version of our OSGi based non-JEE application server. After a very long evaluation, we chose Thymeleaf in our app server to be the same as JSF for JEE.

If you do not mind, I will upload the OSGified version under our groupId to maven-central until the headers are available in the original jars. I hope that in 2.2 or 3.0 the pull request will be accepted.
- groupId: org.everit.osgi.bundles
- artifactId: org.everit.osgi.bundles.org.thymeleaf.thymeleaf
- version: The same
- pom file: The same except the groupId, artifactId and the configuration of the maven-bundle-plugin (see the pull request)

**Comment by danielfernandez** [comment]
First of all, thanks so much for taking the time to implement your pull request, discuss it with us and provide such complete explanations.

After much thinking and discussing about this topic, and especially much learning about OSGi and its ecosystem, we have decided that Thymeleaf will **not** add OSGi metadata to its artifacts, at least for the 2.1 version (and most probably neither for 3.0).

The reasons are:
- Thymeleaf is a complex library, and the amount of imported and exported packages is huge. The complexity of maintaining and especially checking and testing such a big amount of extra metadata would be difficult to justify given the current popularity levels of OSGi, even if it is automatically generated by the Apache Felix plugin (which, from our tests, is not 100% free of issues).
- The Thymeleaf Project is comprised of a number of artifacts besides its _core_ library: `thymeleaf-spring3`, `thymeleaf-spring4`, `thymeleaf-testing`, `thymeleaf-extras-springsecurity3`, `thymeleaf-extras-conditionalcomments`, `thymeleaf-extras-tiles2`, etc. and if OSGi metadata is added to the core `thymeleaf.jar`, in good logic and for the sake of consistency it should be added to all the artifacts. Again, the complexity of managing all this metadata would be difficult to justify.
- Our figures indicate that about 95% of Thymeleaf users use it with Spring, and Spring **dropped** OSGi support in version 3.2 due to the high cost of maintaing such big amounts of metadata. They first derived OSGi support to the _SpringSource EBR_ (Enterprise Bundle Repository) initiative, which was afterwards shut down and deprecated, delegating all such efforts to the (still incubating) _Eclipse  EBR_ project. See:
  - http://docs.spring.io/spring/docs/3.2.x/spring-framework-reference/html/migration-3.2.html#migration-3.2-osgi-users
  - http://spring.io/blog/2013/08/23/spring-framework-3-2-and-the-springsource-ebr
  - http://www.eclipse.org/ebr/
- It doesn't seem 100% logical to add OSGi metadata to thymeleaf once we know most of our users use it with Spring, and that Spring itself is not available anymore in the form of OSGi bundles. And it wouldn't be consistent to add OSGi metadata to just the core jar and ignore the others.
- In general, it seems the tendency for large and medium-sized frameworks and libraries is to move the responsibility of creating OSGi bundles to the OSGi container projects themselves, which many times maintain their own repository of OSGi bundles created on top of the _vanilla_ official library jars.  Exampes of this are the above mentioned _Eclipse EBR_, _Apache ServiceMix_, _RedHat JBoss Fuse_, etc. I've even found out that Apache ServiceMix creates an OSGi bundle for [jasypt](http://www.jasypt.org), another of my open source projects :-)

We might change this opinion in the future, of course, but for now OSGi support will not be added. 

This said, I have myself added OSGi metadata to both [unbescape](http://www.unbescape.org) and [attoparser](http://www.attoparser.org), other two of my open source projects and both of them dependencies of thymeleaf. Both are much, much smaller libraries with no external dependencies, so it made sense for them to add this metadata given the very reduced maintenance effort required, and the possible benefits to people creating OSGi bundles for thymeleaf itself in the future.

**Pull request closed without merging**
