### PR TITLE
Fixes issue #148

### PR DESCRIPTION
**Pull request by chkluwe**
The seconds are also set to zero in `DateUtils#createToday()`

### CODE REVIEW

**Comment by danielfernandez** [comment]
Thanks a lot. 

Your pull request looks OK to me. In order to merge it, and as this is your first pull request, could you please read https://github.com/thymeleaf/thymeleaf/blob/thymeleaf-2.0.16/CONTRIBUTING.markdown and explicitly confirm that you understand and agree with the contribution terms and conditions explained there? A comment in this pull request will be enough. Thanks!

**Comment by danielfernandez** [comment]
Also, if you want to be listed at http://www.thymeleaf.org/team.html as a "contributor" (of course, this is optional), please give me the data you want to appear there about you: name, forum ID, country and email (this has to be non-corporate). You can post these data here or just send me an email.

**Comment by danielfernandez** [comment]
Hi. We are currently planning to release thymeleaf 2.0.17 next Monday or Tuesday... would it be possible to have an answer on this by then? I'd really like this to go into this version... 

Thanks.

**Comment by chkluwe** [comment]
Hi Daniel,

sorry for not coming back to you earlier.

I'm aware of the terms of contribution and agree to them. There might be a slight issue, though. I pushed this commit from work, so the git commit message has my companies email-address (you'll see it with 'git log'). If that's a problem let me know - I'll quickly (! promised) create another pull request with a GMail address.

Even though it is quite an honor to be listed on the Thymeleaf contributors page I'd opt out for now - simply for the reason that I'm selfishly just fixing minor stuff I need to work.

Regards and by the way: thanks for a wonderful template engine!
Chris

**Comment by danielfernandez** [comment]
Ok, thanks a lot Chris. It's not a big issue, but anyway if it's possible for you to create that new pull request with a personal email it will be better. If this is an inconvenience for you, just tell me.

**Comment by chkluwe** [comment]
Hi Daniel,

the new pull request (no. 159) that contains the fix and conforms to the terms is there. I'm closing this one since it's obsolete now.

Regards, Chris

**Pull request closed without merging**
