### PR TITLE
Implementation of the requirement see

### PR DESCRIPTION
**Pull request by opensource21**
https://github.com/thymeleaf/thymeleaf/issues/208.

### CODE REVIEW

**Comment by opensource21** [comment]
I agree with the contribution guideline
https://github.com/thymeleaf/thymeleaf-dist/blob/master/CONTRIBUTING.markdown

**Comment by danielfernandez** [comment]
Thanks a lot. Your code looks good, but I have a question... why do you copy to an array, and then to a list (two copies) when you can simply copy to another list and use `Collections.sort(...)`?

**Comment by opensource21** [comment]
This can be simply explained: Look into the code of `Collections.sort(...)`. There the same thing is done, except that then the Collection is reordered. In our case we want a copy of the original collection to prevent side effects.
So If I use `Collections.sort(...)` I must 

```
  1 Create a new Collection.
  2 Copy all entries into the collection.
  3 Create an array-copy.
  4 Sort the array.
  5 Copy the sorted Array to the collection.
```

With my approach I save step 2 and be a little bit faster. If we assume that `Collections.sort(...)` is the fastest method to sort a collection, this should be the fastest to sort and copy an Collection. 

The drawback is more code, but I find it's acceptable, because it's not to much code which is copied.

Hope this makes it clear.

**Comment by danielfernandez** [comment]
Perfect, thanks a lot. Could you send me an email with your data (name, forum ID, location, email) if you want to be listed as a contributor here: http://www.thymeleaf.org/team.html ?

**Pull request merged**
