### PR TITLE
Added support for server relative links without servlet API (WebContext)

### PR DESCRIPTION
**Pull request by acr92**
See issue #4, please review. Added tests as well which all were successful, so this should work without problems.

### CODE REVIEW

**Comment by acr92** [comment]
Tested now on my own server solution, worked just perfectly. Not able to test on Spring though.

**Comment by danielfernandez** [comment]
Hi, thanks for your code.

I think there's something wrong anyway. As I understand from your code, you are outputting context-relative URLs actually without the context being included at all (which is a value originating from the Servlet API, so this cannot be done without it).

For example, for an URL like `@{/mypath}` in an application deployed at context `myapp`, you would be rendering `/mypath` instead of `/myapp/mypath`, which is what should be done.

Doesn't it make more sense to be able to output **server-relative** URLs without the Servlet API instead? Maybe you are mistaking context-relative for server-relative in your patch?

Thanks

**Comment by acr92** [comment]
Hello,

Thanks for commenting on this. You may be correct, I could be misunderstanding server relative versus context relative.  What I want to achive is simple:

I want to be able to write ${/mypath} without requiring any servlet API, and without a similar modification to what I have done that would not be possible, because it would render a error. I don't use the servlet API for various reasons which is irrelevant.

The patch shouldn't result in errors in any servlet based environment, but i havn't checked that. I know this works for my non-servlet solution.

**Comment by danielfernandez** [comment]
Hi,

Actually, your patch does render context-relative URLs without their context prepended in servlet based environments, which is incorrect.

Would you be willing to re-create your patch allowing **server-relative** URLs instead of **context-relative** URLs to be rendered in servlet-based environments.

When doing this, be careful with URL-rewriting: in no-servlet-based environments the `jsessionid` fragment should not be added to the URL at all, but this should not affect servlet-based environments and these URLs should be created in exactly the same way they are now in web environments (including such URL-rewriting).

Also, please, be sure to read and understand http://www.thymeleaf.org/contributing.html and taking the actions requested there (basically, send me an email agreeing with the terms explained in that page).

Thanks.

**Comment by acr92** [comment]
Hello,

If I understood you right, that would mean that I would have to write **@{~/page/controller/method}** and that would for  both non-servlet and servlet solutions render that as **/page/controller/method**. Is this what you were thinking?

I'll take a look at it tomorrow if that is correct.

**Comment by danielfernandez** [comment]
That `@{~/page/controller/method}` should produce:
- `/page/controller/method` in two scenarios:
  - Non-servlet-based applications.
  - Servlet applications where it has already been established that cookies are active.
- `/page/controller/method;jsessionid=a343114...` in one scenario:
  - Servlet applications where it has not been established whether cookies are active yet.

**Comment by danielfernandez** [comment]
Hi, 

Any news on this? Did you manage to create a new patch?

Thanks,
Daniel.

**Comment by acr92** [comment]
Hello,

Been very busy implementing some backend features on the server that will be using Thymeleaf for its template integration. I'll have a look at it this week as its more focused on user experience, which should give me time to create this patch.

One question though, do you know where I could find a simple thymeleaf example application to run in a Servlet context? So that I can test the patch working correctly.

Regards,
L

**Comment by danielfernandez** [comment]
What about the standard example applications in http://www.thymeleaf.org/documentation.html ? All of them are web applications running in servlet environments...

**Comment by acr92** [comment]
Hah, there we go, never paid much attention to the text below the bold text, as I knew I would have to implement this myself somehow, so I just read the PDFs which were very detailed and straight foreward. I'll get onto it tomorrow or Wednesday.

**Comment by acr92** [comment]
Okay, I think I've got it working.

I've tested with my cookies disabled and enabled on a Tomcat7 servlet container using the first Thymeleaf example. There I have tested absolute, context / and server ~/ relative urls. All working great.

On my own non servlet based solution I've tested absolute (works), context / (fails, as it should) and server ~/ (works). I also don't have any jsessionid appended to my non-servlet solution.

Pull request comming soon, just needs to clean up the code. Will email you as well.

EDIT: Also tested out some bogus urls, like @{b/}, and that will fail as well.

**Comment by danielfernandez** [comment]
Great news! :-) I'm glad you made it work.

Also, please, remember to follow the steps in
http://www.thymeleaf.org/contributing.html so that I can merge your patch
into the codebase.

Regards,
Daniel.

On 4 July 2012 12:13, Arne-Christian Blystad <
reply@reply.github.com

**Comment by acr92** [comment]
Closing this as I'll submit a new pull request in few minutes.

**Pull request closed without merging**
