### PR TITLE
improve error handling for jackson initialization

### PR DESCRIPTION
**Pull request by anschnapp**
should fix the problem when a NoSuchMethod appears on jackson initialization, see issue ticket:
https://github.com/thymeleaf/thymeleaf/issues/530

### CODE REVIEW

**Comment by danielfernandez** [comment]
Thanks. I'm fine with your code.

In order to accept your contribution, I would need you to read the guidelines for contributing to this repository at https://github.com/thymeleaf/thymeleaf/blob/dd663b34a36892ab6e10f1c473fa75c29d106c06/CONTRIBUTING.markdown and to explicitly agree to them (a comment here will suffice).

**Comment by anschnapp** [comment]
I read the guidelines for contributing to this repository and agree to them.

**Comment by danielfernandez** [comment]
Already in `3.0.2-SNAPSHOT`

**Comment by danielfernandez** [comment]
@git2snap Thanks for your contributions. I would be happy to add you as a contributor here: http://www.thymeleaf.org/team.html, unless you prefer to opt-out. In order to do so, I would need a (real) name to be displayed and a country.

**Pull request merged**
