### PR TITLE
Make Thymleaf cache more testable, enabling cache metrics monitoring.

### PR DESCRIPTION
**Pull request by rynkowsw**
1) Removed final from class definition, by this change  cache is more testable
2) Removed condition that metrics are incremented only at TRACE log level
3) Added getter for the metrics, this  helps in cache monitoring
4) Added hit and miss ratio metric
5) Change metrics variable type from AtomicLong to volatile long -  performance reason.

### CODE REVIEW

**Comment by danielfernandez** [comment]
Thanks so much @rynkowsw!

Before accepting your contribution, however, please make sure you carefully read and understand the project contribution guidelines explained at https://github.com/thymeleaf/thymeleaf/blob/d1d5e5289b378c02e8f33a5fe32fa22f3641e426/CONTRIBUTING.markdown

I will need you to explicitly agree to the terms above. A comment here will suffice. Thanks again.

**Comment by danielfernandez** [comment]
As for your changes, I've been reviewing your code and I have several comments.

Let's start by the last one:

> Change metrics variable type from AtomicLong to volatile long - performance reason.

There is a problem here. `volatile long` variables do not have the same behaviour as `AtomicLong`. Whereas `volatile` would ensure that the variable values are adequately synchronized among all threads during all _access_ operations, it would still require a surrounding `synchronized` block for the required increment operations being performed at `StandardCache`.

The reason is `i++` actually performs two accesses: one _read_ and one _write_, and `volatile` would not guarantee that no thread can read the variable's value before a different thread writes the incremented value. So it's either having the `synchronized` block, or using `AtomicLong` as it is already been used. `AtomicLong` (which contains a `volatile long` inside) provides an `incrementAndGet()` method which adequately synchronizes all accesses required during the whole _increment_ operation, but in a more low-level-optimized manner than merely adding the `synchronized` block.

So unless there is something I'm missing here, we will stay with `AtomicLong` for those counters.

> Removed condition that metrics are incremented only at TRACE log level

Related with my previous comment, I think counters should not be updated always, only when there is a specific interest on doing that (e.g. logging or monitoring). The reason for this is that incrementing counters means dealing with an amount of synchronization, and synchronization goes against performance. Even if `AtomicLong` does not use `synchronized` blocks underneath (it uses a _swap_ operation provided by `Unsafe`), it still needs to read and write an internal `volatile` variable, which means cross-thread synchronization operations need to be done.

Being the cache a hugely critical component performance-wise, I don't think adding at least 2 `volatile` accesses to each cache access is a good idea, even if there are other uses of `volatile` in the template model — but those are 100% needed in general, while these would be _just in case somebody wants to monitor_. That's why the counters were only being applied when logging was set to `TRACE`.

So what I would propose here would be to keep these counters _optional_ as they are today, but unlink them from the logger level. My proposal here would be to add a new `boolean enableCounters` flag, `false` by default, and a new constructor that includes all of the fields of the current _complete_ constructor plus the new flag. So:

``` java
// Existing constructor
public StandardCache(final String name, final boolean useSoftReferences, 
        final int initialCapacity, final int maxSize, 
        final ICacheEntryValidityChecker<? super K, ? super V> entryValidityChecker, 
        final Logger logger) {
    this(name, useSoftReferences, initialCapacity, maxSize, entryValidityChecker, logger, false);
}

// New constructor
public StandardCache(final String name, final boolean useSoftReferences, 
        final int initialCapacity, final int maxSize, 
        final ICacheEntryValidityChecker<? super K, ? super V> entryValidityChecker, 
        final Logger logger, final boolean enableCounters) {

        ...
        this.logger = logger;
        this.traceExecution = (logger != null && logger.isTraceEnabled());
        // We will enable the counters separately from whether execution should be traced
        this.enableCounters == this.traceExecution || enableCounters;
        ...

```

So the counter increments would depend on this new flag:

``` java
...
if (this.enableCounters) {
    incrementReportEntity(this.getCount);
    incrementReportEntity(this.hitCount);
}
if (this.traceExecution) {
    this.logger.trace(
            "[THYMELEAF][{}][{}][CACHE_HIT] Cache hit in cache \"{}\" for key \"{}\".", 
            new Object[] {TemplateEngine.threadIndex(), this.name, this.name, key});
    outputReportIfNeeded();
}
...
```

So after applying this, the end result is that we would still have a `StandardCache` class able to _optionally_ keep hit/miss counters, but do it even if we don't want to apply `TRACE`-level logging.

> Added getter for the metrics, this helps in cache monitoring

Yes, why not. Note that even if the counters will still be `AtomicLong`, these getters should return `long` in order to protect the internal counter objects (which are mutable).

> Added hit and miss ratio metric

I wouldn't oppose this as a general concept, but take into consideration several things that make this much more complicated than it might seem:

Given these ratios involve more than one counter, and there is no `synchronized` block around the sequences of increments in the cache's `get` or `put` methods, the figures returned here should not be considered _accurate_ and this should be documented in javadoc. If you look at the block of code above:

``` java
if (this.enableCounters) {
    incrementReportEntity(this.getCount);
    incrementReportEntity(this.hitCount);
}
```

Your ratio `hitRatio = hitCount / getCount` could be computed while another thread has already incremented the first counter (`get`), but hasn't updated the second one yet (`hit`). We could avoid this by adding a `synchronized` block in the code above and all equivalent (i.e. in `get` and `put`), but that would be IMHO overkill. I would not be worried about these _ratios_ not being terribly accurate.

However, note here that the existence of these ratios turns the order in which the counters are incremented very important. The reason is, if in the code above we incremented `hit` before `get`, the ratios could end up giving results > 100% if a thread different to the one that is computing these ratios has incremented one counter but not the other one.

This lack of accuracy, and the fact that you can –and should– compute one ratio as 100% minus the other (`1` minus the other, in fact), will mean that you will have to describe one of your ratios as a "minimum" and the other one as a "maximum". I think the correct thing to do here is to make the _miss_ ratio a maximum (_"miss ratio is at most 15%"_), and the _hit_ ratio a minimum (_"hit ratio is at least 85%"_). 

So you should be computing the _hit ratio_, and then returning _miss ratio_ as `1 - getHitRatio()`. And when computing the _hit ratio_, given the importance of the order in which counters are increased, you should first read `hitCount`, and only then `getCount`. That will guarantee you that you will never end up with a ratio > 100% because you'd be reading the counters in the inverse order they are incremented. And that will be also the reason why that _hit radio_ will only be a minimum and not an accurate figure.

Last, note that these ratios could be also output at the `outputReportIfNeeded()` method, but in such case I would never call `get()` for each of the counters more than once inside that `synchronized` block that does the real output. So first obtain all the values in the correct order (`hit`, `miss`, `put`, `get`) and _only once_, then compute the ratios without calling `getHitCount()` or `getMissCount()` but instead computing first `hitRatio = hit / get`, then doing `missRatio = 1 - hitRatio`, then output everything.

> Removed final from class definition, by this change  cache is more testable

Here I would need your help to better understand the need. The reason this class is `final` is precisely that it is a very complex class which shouldn't really be messed around with, and that by making it final we give the runtime the opportunity to apply some optimizations and remove polymorphism-oriented structures — though whether this last point really makes a difference or not is a hot matter of debate.

Now, as for testing... this class implements the `org.thymeleaf.cache.ICache` interface, so I don't think mocking this interface should be an issue for testing. And I don't think there should be many reasons to specifically mock `StandardCache` and not the `ICache` interface during testing.

If the idea is to extend the functionality of `StandardCache` (which I presume would not be done in tests), then IMHO composition should be used, more than extension.

But again, I might be missing something here on the need to make this class non-final. Could you please elaborate on the specific testing needs that would require this change?

---

And last, remember that Thymeleaf 3.0 is already the stable branch. So it would be great if you could perform the changes against the 3.0 branch, and then once they are stabilised and merged create an equivalent patch for the (now legacy) 2.1 branch. But 3.0 first, if possible.

Thanks again!

**Comment by danielfernandez** [comment]
Hello again @rynkowsw 

I have been reviewing your latest changes, even if I understand they are still partial work. My comments so far:

**1.** It seems when adding the new constructor (the one that adds the `enableCounters` flag) you actually removed the fourth constructor that existed before (the one that had all the arguments but the new flag). But the idea was to add a new constructor, not to replace one of the existing ones…

**2.** The initialization of the `enableCounters` flag at the constructor does not take into account the value of the `traceExecution` flag. If the latter flag is true, `enableCounters` should always be, too, independently of the value of the constructor argument. That's why I wrote my example above like:

```java
// We will enable the counters separately from whether execution should be traced
this.enableCounters == this.traceExecution || enableCounters;
```

This actually makes you use an (unnecessary) double check when incrementing the counters, like you do here:

```java
private void incrementReportEntity(final AtomicLong entity) {
    if (this.traceExecution || this.enableCounters) {
        entity.incrementAndGet();
    }
}
```

**3.** You still seem to be working against the 2.1 branch, instead of the preferred 3.0 one. Please remember that there have been changes to these classes in 3.0 that might affect your code: for instance, in 3.0 there is no more a *fragment cache* separate from the *template cache*, and the key classes used in the cache entries have changed.

**4.** Your latest commit seems to have been generated with a corporate (non-personal) user identification, which is actually not linked by GitHub to your public GitHub account. Please note that according to the contribution terms and conditions, all contributions must be made as a private individual acting in your own name.

**5.** Related to the last point, please remember that you haven't yet accepted the terms of the Thymeleaf Contributot Agreement mentioned in one of my previous comments.

Thanks for all your work!

**Comment by rynkowsw** [comment]
1) I fixed it. 
2) OK
3) Today i update changes for 3.0
4) It was my mistake. 
5) I accept the terms of the Thymeleaf Contributot Agreement

**Comment by rynkowsw** [comment]
Hi @danielfernandez 
Thanks for your time, and sorry for my mistakes. 
1) I fixed it. 
2) OK 
3) Today I added it to 3.0 dev branch
4) It was my mistake, done in git config file. As long as i made most all my commits to work, then i keep the same gitconfig file in private computer. I missed this meta information at commits.  
5) I accept Thymeleaf Contributot Agreement

**Comment by rynkowsw** [comment]
Hi @danielfernandez 
Thanks for your time, and sorry for my mistakes. 
1) I fixed it. 
2) OK 
3) Today I added it to 3.0 dev branch
4) Since most commits i doing to the work, so I keep the same gitconfig file in private computer. I missed this meta information at this commits.  
5) I accept Thymeleaf Contributot Agreement

**Comment by danielfernandez** [comment]
Closing this — #558 has been merged.

**Pull request closed without merging**
