### PR TITLE
added skip processing variable with URL value inlined in JS code

### PR DESCRIPTION
**Pull request by blandger**
I added piece of code to escape processing URL variable values inlined into JS code. URLS has been spoiled as described in tread:
http://forum.thymeleaf.org/Spring-login-expression-example-how-avoid-error-tp4025561p4025572.html

### CODE REVIEW

**Comment by danielfernandez** [comment]
Thanks a lot for your patch and effort, Yuriy.

Actually, escaping the `/` symbol in javascript as `\/` is something allowed and standardized, and your URLs should work perfectly like that in any browser. Not allowing such escaping should be considered a bug in a JavaScript engine.

I understand nevertheless this might look a bit _strange_ to the eye. The reason this character can be escaped like that is to forbid the appearance of the forbidden sequence `</` inside a script, which would close the script before time. If the `/` symbol is not preceded by `<`, this escaping is not necessary (but allowed).

Thymeleaf performs this escaping always, but I agree it would be nicer to the eye to do it only when the escaped character is really preceded by `<`.

So I would like to ask you to rebuild your patch by modifying the `org.thymeleaf.utils.StringUtils#escapeJavaAny(...)` method, specifically the condition at line 696, so that this escaping is only performed if the previous character is a `<` (and there is such previous character).

Also, please, when you submit your patch --if you do ;-)-- make sure you read https://github.com/thymeleaf/thymeleaf/blob/2.0-master/CONTRIBUTING.markdown and explicitly state in your pull request you agree with the terms and Contributor License Agreement explained there.

**Comment by blandger** [comment]
Subject: [thymeleaf] added skip processing variable with URL value inlined in JS code (#114)
Date: Wednesday, January 30, 2013

Hi, Daniel.
See comments below.

You wrote: Wednesday, January 30, 2013

Thanks a lot for your patch and effort, Yuriy.
Actually, escaping the / symbol in javascript as \/ is something allowed and standardized, and your URLs should work perfectly like that in any browser. 

Unfortunately I tried to open them in browser but without expected result. 

Not allowing such escaping should be considered a bug in a JavaScript engine.

Probably you are right, I'm not familiar with that topic. 

I understand nevertheless this might look a bit strange to the eye. The reason this character can be escaped like that is to forbid the appearance of the forbidden sequence </ inside a script, which would close the script before time. If the / symbol is not preceded by <, this escaping is not necessary (but allowed).
Thymeleaf performs this escaping always, but I agree it would be nicer to the eye to do it only when the escaped character is really preceded by <.

Can you specify exact url example(s) that should allow such escape processing ?

So I would like to ask you to rebuild your patch by modifying the org.thymeleaf.utils.StringUtils#escapeJavaAny(...) method, specifically the condition at line 696, so that this escaping is only performed if the previous character is a < (and there is such previous character).

Did you mean condition in code:

> ```
>     Matcher matcher = WEB_SITE_FULL_EVAL_PATTERN.matcher(text);
>     if (matcher.find()) {
> ```

or you talk about code:

> ```
>             switch (c) {
>                 case '\\' :
> ```

Might be my local code points to wrong line.

Also, please, when you submit your patch --if you do ;-)-- make sure you read https://github.com/thymeleaf/thymeleaf/blob/2.0-master/CONTRIBUTING.markdown and explicitly state in your pull request you agree with the terms and Contributor License Agreement explained there.

Yes, I've read them, did I miss something somewhere?

**Comment by danielfernandez** [comment]
Hi again Yuriy

> Unfortunately I tried to open them in browser but without expected result.

Hmmm... try this, it should work perfectly:

``` html
<!DOCTYPE html>
<html>
  <head>
    <title>Testing JavaScript escaping</title>
    <script>
      // <![CDATA[
        function doIt() {
          var url = 'http:\/\/www.thymeleaf.org\/documentation.html';
          alert('Redirecting to: ' + url);
          document.location.href = url;
        }
      // ]]>
    </script>
  </head>
  <body>
    <div>
      <a href="#" onclick="doIt()">Do it!</a>
    </div>
  </body>
</html>
```

> Can you specify exact url example(s) that should allow such escape processing ?

Not URLs only. I mean that the modification could consist in performing only the `/` escaping if the symbol before the `/` is a `<`, and not in the rest of cases. Be it an URL or whatever. No need for pattern-matching.

> Might be my local code points to wrong line.

You are looking at your own patched copy of `StringUtils`, and I meant the one at the master branch: https://github.com/thymeleaf/thymeleaf/blob/2.0-master/src/main/java/org/thymeleaf/util/StringUtils.java#L696

Regards,
Daniel.

**Comment by blandger** [comment]
I tested that code finally.
Looks like it works without changes. Don't know that had happen with that code before, but it definitely hadn't work.

**Comment by danielfernandez** [comment]
FYI, Thymeleaf 2.0.16 includes a modification to JavaScript escaping so that `/` is only escaped after `<`. See https://github.com/thymeleaf/thymeleaf/pull/132

**Pull request closed without merging**
