### PR TITLE
Fixes #595 - Use {@value} in Javadoc to ensure constant values match …

### LINKED ISSUE #595: Constant values in Javadoc for StandardCacheManager do not match implementation
Some of the constant values in StandardCacheManager do not match the values specified in the Javadoc, for example DEFAULT_TEMPLATE_CACHE_INITIAL_SIZE has an actual value of 20, but the Javadoc says 10.

Fix in the PR is just to use {@value ...} Javadoc tags, so that the values are always in sync.

### PR DESCRIPTION
**Pull request by pgpx**
…documentation.

### CODE REVIEW

**Comment by ultraq** [comment]
TIL about the `@value` javadoc annotation 👍

**Review by danielfernandez — COMMENTED** [review]
Thanks for your modifications, which of course make a lot of sense. I'm however a bit confused, because according to the current JavaDoc specification for `{@value}` http://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html#CHDDCDHH it seems you should be writing these either like `{@value #CONSTANT}` or simply `{@value}`, but you don't use the `#` and yet it seems to work…

I don't see warnings being issued when generating javadoc with your modifications, but anyway I wonder: is allowing this syntax normal behaviour? Would it be possible for you to adapt it to the spec?

Thanks!

**Comment by pgpx** [comment]
Good point - I've always used `{@value #CONSTANT}` before (not sure why I didn't use that here -
 probably IntelliJ completion).  I actually didn't know about `{@value}`, and that would seem to be a better choice here anyway (more concise/less redundant), so I've pushed another commit that uses that.  You'll need to squash the commits if you like it.

**Review by danielfernandez — APPROVED** [review]

**Comment by danielfernandez** [comment]
Merged. Thanks!

**Pull request merged**
