### PR TITLE
Add new method(multipleReplace) in #strings

### PR DESCRIPTION
**Pull request by sunil0791**
Enhanced version of replace method:
Use Case: 

> > Consider i want to replace " " with "-" and "." with "@" of the word
> > "Ap p.le", it would'nt be possible using replace.
> > using ${#strings.multipleReplace('Ap p.le',{' ','.'},{'-','@'})}
> > output will be "Ap-p@le"

Useful in providing href link which contains product name in URL where
in we have to replace " " and "." to "-" for SEO in web applications.

The file is formatted using Eclipse which has removed blank spaces in the file (by default) and has arranged the code. please look for multipleReplace method

### CODE REVIEW

**Comment by danielfernandez** [comment]
Thanks a lot for your pull request. Your method looks fine and I like the feature, I'd be happy to merge it for 2.0.17. Nevertheless, there are a couple of issues with your code:
- There is no null validation for arguments at the beginning of the method (target, before and after). See the rest of the methods in that class to see how this is performed.
- There is an "if" block without brackets, which goes against our code standards.
- The diff shows the whole file as modified because of your eclipse IDE plugin, which is removing all whitespaces and very probably also changing the file's line feeds. Please correct this so that your diff only shows your code as modified, or else it would be quite difficult to track exactly what differences are introduced by your commit.

Also, make sure you read https://github.com/thymeleaf/thymeleaf/blob/thymeleaf-2.0.16/CONTRIBUTING.markdown and please add a comment to your pull request explicitly stating you agree to the terms established there, with a link to this file. This is a requirement for all first-time pull requests from anyone.

**Comment by danielfernandez** [comment]
Oh, and by the way: it would be great if you could also add "array_", "list_" and "set*" versions of your new method, as there currently exist for most other operations...

**Comment by sunil0791** [comment]
Sure Daniel, I would be more than happy to do it, will keep you updated for the same.

**Comment by sunil0791** [comment]
I have read (https://github.com/thymeleaf/thymeleaf/blob/thymeleaf-2.0.16/CONTRIBUTING.markdown)  and 
I agree to the Terms & Conditions of Thymeleaf as specified in the above link.

**Pull request merged**
