### PR TITLE
Various edits to CONTRIBUTING.markdown to improve grammar, spelling, and verbiage

### PR DESCRIPTION
**Pull request by jlacar**
These are edits to the individual contributor terms and agreement to improve the verbiage, correct misspellings, capitalization, and typos, and the change to the coding standard around the use of "parameter" instead of "argument" and comments for non-trivial algorithms.

### CODE REVIEW

**Comment by ultraq** [comment]
So does this supersede #584 (and mean that #584 can be closed) ?

**Comment by jlacar** [comment]
Yes, it does. Sorry, I should have mentioned that in the PR comment.

**Comment by ultraq** [comment]
Looks good to me 👍 

@danielfernandez ?

**Review by danielfernandez — APPROVED** [review]

**Comment by danielfernandez** [comment]
Merged! I'll now copy the new file to all repositories. Thanks Junilu!

**Pull request merged**
