### PR TITLE
OSGify

### PR DESCRIPTION
**Pull request by oliverlietz**
* add Maven Bundle Plugin and OSGi Versioning annotations
* change packaging to bundle
* add package info with version to each package
* enable baselining

This is the least possible change to OSGify Thymeleaf and provide proper versioned packages.

This issue should serve as a basis for discussion to provide Thymeleaf as OSGi bundle in the future. Two attempts (#32, #280) were rejected in the past for older versions of Thymeleaf.

I rebuilt every release starting with 3.0.0.RELEASE (using version 3.0.0 for each package) and ended up with following package versions:

```
[INFO] Baseline Report - Generated by Apache Felix Maven Bundle Plugin on 2017-08-18T14:16Z based on Bnd - see http://www.aqute.biz/Bnd/Bnd
[INFO] Comparing bundle thymeleaf version 3.0.8-SNAPSHOT to version 3.0.7.RELEASE
[INFO] 
[INFO]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
[INFO] = ================================================== ========== ========== ========== ========== ==========
[INFO]   org.thymeleaf                                      unchanged  5.0.0      5.0.0      5.0.0      -         
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   org.thymeleaf.cache                                unchanged  3.1.0      3.1.0      3.1.0      -         
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   org.thymeleaf.context                              unchanged  3.0.0      3.0.0      3.0.0      -         
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   org.thymeleaf.dialect                              unchanged  3.0.0      3.0.0      3.0.0      -         
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   org.thymeleaf.engine                               unchanged  3.2.0      3.2.0      3.2.0      -         
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   org.thymeleaf.exceptions                           unchanged  3.0.0      3.0.0      3.0.0      -         
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   org.thymeleaf.expression                           unchanged  3.1.0      3.1.0      3.1.0      -         
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   org.thymeleaf.inline                               unchanged  3.0.0      3.0.0      3.0.0      -         
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   org.thymeleaf.linkbuilder                          unchanged  3.0.0      3.0.0      3.0.0      -         
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   org.thymeleaf.messageresolver                      unchanged  3.0.0      3.0.0      3.0.0      -         
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   org.thymeleaf.model                                unchanged  3.0.0      3.0.0      3.0.0      -         
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   org.thymeleaf.postprocessor                        unchanged  3.0.0      3.0.0      3.0.0      -         
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   org.thymeleaf.preprocessor                         unchanged  3.0.0      3.0.0      3.0.0      -         
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   org.thymeleaf.processor                            unchanged  3.0.0      3.0.0      3.0.0      -         
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   org.thymeleaf.processor.cdatasection               unchanged  3.0.0      3.0.0      3.0.0      -         
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   org.thymeleaf.processor.comment                    unchanged  3.0.0      3.0.0      3.0.0      -         
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   org.thymeleaf.processor.doctype                    unchanged  3.0.0      3.0.0      3.0.0      -         
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   org.thymeleaf.processor.element                    unchanged  3.0.0      3.0.0      3.0.0      -         
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   org.thymeleaf.processor.processinginstruction      unchanged  3.0.0      3.0.0      3.0.0      -         
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   org.thymeleaf.processor.templateboundaries         unchanged  3.0.0      3.0.0      3.0.0      -         
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   org.thymeleaf.processor.text                       unchanged  3.0.0      3.0.0      3.0.0      -         
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   org.thymeleaf.processor.xmldeclaration             unchanged  3.0.0      3.0.0      3.0.0      -         
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   org.thymeleaf.standard                             unchanged  3.0.0      3.0.0      3.0.0      -         
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   org.thymeleaf.standard.expression                  unchanged  3.0.0      3.0.0      3.0.0      -         
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   org.thymeleaf.standard.inline                      unchanged  3.0.0      3.0.0      3.0.0      -         
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   org.thymeleaf.standard.processor                   unchanged  3.0.0      3.0.0      3.0.0      -         
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   org.thymeleaf.standard.serializer                  unchanged  3.0.0      3.0.0      3.0.0      -         
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   org.thymeleaf.standard.util                        unchanged  3.0.0      3.0.0      3.0.0      -         
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   org.thymeleaf.templatemode                         unchanged  3.0.0      3.0.0      3.0.0      -         
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   org.thymeleaf.templateparser                       unchanged  3.0.0      3.0.0      3.0.0      -         
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   org.thymeleaf.templateparser.markup                unchanged  3.0.0      3.0.0      3.0.0      -         
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   org.thymeleaf.templateparser.markup.decoupled      unchanged  3.0.0      3.0.0      3.0.0      -         
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   org.thymeleaf.templateparser.raw                   unchanged  3.0.0      3.0.0      3.0.0      -         
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   org.thymeleaf.templateparser.reader                unchanged  3.0.0      3.0.0      3.0.0      -         
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   org.thymeleaf.templateparser.text                  unchanged  4.0.0      4.0.0      4.0.0      -         
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   org.thymeleaf.templateresolver                     unchanged  3.1.0      3.1.0      3.1.0      -         
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   org.thymeleaf.templateresource                     unchanged  3.1.0      3.1.0      3.1.0      -         
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO]   org.thymeleaf.util                                 unchanged  3.3.0      3.3.0      3.3.0      -         
[INFO] -----------------------------------------------------------------------------------------------------------
[INFO] Baseline analysis complete, 0 error(s), 0 warning(s)
```

### CODE REVIEW

**Comment by danielfernandez** [comment]
Thank you very much for your work @oliverlietz 

Please review my comments on this topic 3 years ago here https://github.com/thymeleaf/thymeleaf/pull/280#issuecomment-50977114. I believe my comments stand, perhaps even more given I have the feel that OSGi use has been in decline since then… would you be able to provide any new arguments to this discussion that would deem maintaining OSGi metadata for the Thymeleaf core more convenient?

Also, please note that I still consider this to hold nowadays:

> In general, it seems the tendency for large and medium-sized frameworks and libraries is to move the responsibility of creating OSGi bundles to the OSGi container projects themselves, which many times maintain their own repository of OSGi bundles created on top of the vanilla official library jars. Exampes of this are the above mentioned Eclipse EBR, Apache ServiceMix, RedHat JBoss Fuse, etc. I've even found out that Apache ServiceMix creates an OSGi bundle for jasypt, another of my open source projects :-)

**Comment by oliverlietz** [comment]
I have analyzed the [_Top 100 Java libraries_](http://blog.takipi.com/the-top-100-java-libraries-in-2016-after-analyzing-47251-dependencies/) and most non-Spring projects provide OSGi metadata themselves:

Group ID | Artifact ID | Version | Bundle Symbolic Name | Comment
---|---|---|---|---
junit|junit|4.12||
org.slf4j|slf4j-api|1.8.0-alpha2|slf4j.api|
com.google.guava|guava|23|com.google.guava|
log4j|log4j|1.2.17|log4j|
commons-io|commons-io|2.5|org.apache.commons.io|
org.slf4j|slf4j-log4j12|1.8.0-alpha2|slf4j.log4j12|
org.mockito|mockito-all|2.0.2-beta|org.mockito.mockito-all|
commons-lang|commons-lang|2.6|org.apache.commons.lang|
ch.qos.logback|logback-classic|1.2.3|ch.qos.logback.classic|
org.apache.commons|commons-lang3|3.6|org.apache.commons.lang3|
javax.servlet|servlet-api|3.0-alpha-1||newer release with different coordinates is bundle
org.apache.httpcomponents|httpclient|4.5.3||bundle with different coordinates
org.springframework|spring-context|4.3.10.RELEASE||Spring
com.fasterxml.jackson.core|jackson-databind|2.9.0|com.fasterxml.jackson.core.jackson-databind|
commons-codec|commons-codec|1.1|org.apache.commons.codec|
org.mockito|mockito-core|2.8.47|org.mockito.mockito-core|
org.springframework|spring-test|4.3.10.RELEASE||Spring
joda-time|joda-time|2.9.9|joda-time|
com.google.code.gson|gson|2.8.1|com.google.gson|
org.testng|testng|6.11|org.testng|
org.slf4j|jcl-over-slf4j|1.8.0-alpha2|jcl.over.slf4j|
org.springframework|spring-webmvc|4.3.10.RELEASE||Spring
commons-logging|commons-logging|1.2|org.apache.commons.logging|
org.springframework|spring-core|4.3.10.RELEASE||Spring
mysql|mysql-connector-java|5.1.43|com.mysql.jdbc|
org.codehaus.jackson|jackson-mapper-asl|1.9.13|jackson-mapper-asl|
org.springframework|spring-web|4.3.10.RELEASE||Spring
com.fasterxml.jackson.core|jackson-core|2.9.0|com.fasterxml.jackson.core.jackson-core|
javax.servlet|javax.servlet-api|4.0.0|javax.servlet-api|
commons-collections|commons-collections|3.2.2|org.apache.commons.collections|
org.slf4j|slf4j-simple|1.8.0-alpha2|slf4j.simple|
commons-cli|commons-cli|1.4|org.apache.commons.cli|
org.springframework|spring-beans|4.3.10.RELEASE||Spring
org.hamcrest|hamcrest-all|1.3||
com.h2database|h2|1.4.196|org.h2|
org.springframework|spring-jdbc|4.3.10.RELEASE||Spring
org.springframework|spring-orm|4.3.10.RELEASE||Spring
org.springframework|spring-tx|4.3.10.RELEASE||Spring
com.fasterxml.jackson.core|jackson-annotations|2.9.0|com.fasterxml.jackson.core.jackson-annotations|
org.springframework|spring-aop|4.3.10.RELEASE||Spring
org.hibernate|hibernate-validator|6.0.1.Final||
javax.servlet|jstl|1.2||newer release with different coordinates is bundle
org.json|json|20170516|json|
commons-dbcp|commons-dbcp|1.4|org.apache.commons.dbcp|
commons-fileupload|commons-fileupload|1.3.3|org.apache.commons.fileupload|
org.hibernate|hibernate-entitymanager|5.1.10.Final|org.hibernate.entitymanager|
org.springframework|spring-context-support|4.3.10.RELEASE||Spring
org.hibernate|hibernate-core|5.1.10.Final|org.hibernate.core|
org.easymock|easymock|3.4|org.easymock|
org.codehaus.jackson|jackson-core-asl|1.9.13|jackson-core-asl|
org.hamcrest|hamcrest-library|1.3||
javax.mail|mail|1.4.7|javax.mail|
org.hsqldb|hsqldb|2.3.5|org.hsqldb.hsqldb|
commons-httpclient|commons-httpclient|3.1||newer release with different coordinates is bundle
org.assertj|assertj-core|3.8.0|org.assertj.core|
com.google.inject|guice|4.1.0|com.google.inject|
com.google.code.findbugs|jsr305|3.0.2|org.jsr-305|
org.apache.zookeeper|zookeeper|3.5.3-beta|org.apache.hadoop.zookeeper|
ch.qos.logback|logback-core|1.2.3|ch.qos.logback.core|
org.apache.hadoop|hadoop-core|1.2.1||
org.apache.velocity|velocity|1.7|org.apache.velocity|
org.hamcrest|hamcrest-core|1.3||
org.aspectj|aspectjrt|1.8.10||broken manifest
commons-beanutils|commons-beanutils|1.9.3|org.apache.commons.beanutils|
org.apache.httpcomponents|httpcore|4.4.6||
javax.servlet.jsp|jsp-api|2.2.1-b03||newer release with different coordinates is bundle
org.apache.maven|maven-plugin-api|3.5.0||
org.projectlombok|lombok|1.16.18||
javax.inject|javax.inject|1||no manifest
org.aspectj|aspectjweaver|1.8.10||broken manifest
org.apache.hadoop|hadoop-common|2.7.4||
org.springframework.boot|spring-boot-starter-web|1.5.6.RELEASE||Spring
org.bukkit|bukkit|||not on Central
xerces|xercesImpl|2.11.0||
org.eclipse.jetty|jetty-server|9.4.7.RC0|org.eclipse.jetty.server|
javax.validation|validation-api|2.0.0.Final|javax.validation.api|
org.slf4j|log4j-over-slf4j|1.8.0-alpha2|log4j.over.slf4j|
commons-configuration|commons-configuration|1.1|org.apache.commons.configuration|
cglib|cglib-nodep|3.2.5||
com.googlecode.json-simple|json-simple|1.1.1|com.googlecode.json-simple|
org.springframework.security|spring-security-web|4.2.3.RELEASE||Spring
org.springframework.security|spring-security-config|4.2.3.RELEASE||Spring
cglib|cglib|3.2.5||
org.elasticsearch|elasticsearch|5.5.2||
com.google.protobuf|protobuf-java|3.4.0|com.google.protobuf|
org.apache.hadoop|hadoop-client|2.7.4||
org.javassist|javassist|3.22.0-CR2|javassist|
org.springframework.boot|spring-boot-starter-test|1.5.6.RELEASE||Spring
com.thoughtworks.xstream|xstream|1.4.10-java7|xstream|
org.jsoup|jsoup|1.10.3|org.jsoup|
org.powermock|powermock-module-junit4|1.7.1||
io.netty|netty-all|4.0.50.Final||
org.codehaus.plexus|plexus-utils|3.1.0||
org.codehaus.groovy|groovy-all|2.4.12|groovy-all|
org.slf4j|slf4j-jdk14|1.8.0-alpha2|slf4j.jdk14|
org.powermock|powermock-api-mockito|1.7.1||
org.mortbay.jetty|jetty|6.1.26|org.mortbay.jetty.server|
dom4j|dom4j|1.4-dev-8||
org.springframework.security|spring-security-core|4.2.3.RELEASE||Spring
org.apache.lucene|lucene-core|6.6.0||

It is time-wasting and error-prone to manage OSGi metadata not in the project itself.
For Thymeleaf it means maintaining a fork which provides proper package versions and e.g. maintaining a `pom.xml` and `bundle.info` at [ServiceMix](https://github.com/apache/servicemix-bundles) to get visibility.

Managing OSGi metadata in Thymeleaf itself means adjusting the version in package info when baselining spits out a warning or error only. And it's much more convenient to work with the dependency itself instead of a wrapper with different coordinates.

**Comment by oliverlietz** [comment]
@danielfernandez, I haven't found any reliable numbers which prove or disprove a decline of OSGi. As I'm doing mostly enterprise OSGi web projects, but also playing with OSGi on IoT platforms and desktop (JavaFX) I'm somewhat biased.
My colleagues are doing Spring, Java EE and OSGi projects also (I'm not aware of any other platform like e.g. Vert.x) and I would say Spring lost some market share to Java EE after its positive impact on Java EE.
OSGi has a healthy community and the [upcoming OSGi R7](http://blog.osgi.org/2017/03/new-osgi-r7-spec-drafts-published.html) brings several new specifications.
Developers unaware of OSGi should have a look at this [incomplete list of projects](https://en.wikipedia.org/wiki/OSGi#Projects_using_OSGi).

**Comment by danielfernandez** [comment]
@oliverlietz thanks for all the data and your comments.

I understand there are many popular projects out there including OSGI metadata — it's a mandatory requirement for all Apache Commons modules, for instance. Anyway, the part about the popularity of OSGi, as I said, was just a *feel* as I see almost no new articles on the topic (which, I admit, was popular 6-8 years ago) and in all the 6 years of Thymeleaf life we received no requests on the topic besides the tickets you already referenced. Anyway, it's perfectly normal than OSGi may have different weights in different software fields.

Also, right now we estimate the number of users that use Thymeleaf along with Spring in approx 95%, judging from our download figures and also our latest user survey. Spring which, by the way, and as a mere side comment, is definitely *not losing market* at all :), see for instance [the incredible growth rate of Spring Boot](https://twitter.com/pieterhumphrey/status/808433150632202240), which is in fact the main factor of Thymeleaf's growth itself. 

So having a 5% of non-Spring users, the final amount of Thymeleaf users that besides not using Spring have OSGi requirements is most probably tiny.

Does this by itself make OSGi irrelevant for us? no, of course not, even a 0,1% would be important! But relative weight is something to take into careful consideration when several other factors appear:

1. Proper OSGi integration imposes constraints on library code that Thymeleaf was not built in mind with. For instance, Thymeleaf does use at several parts of its code hot-loading of classes via the likes of a `Class.forName(...)` mechanism (a bit more complex than that, actually), and to the best of my knowledge this is not something that OSGi is normally happy about.

2. Thymeleaf has a dependency on OGNL when used without Spring, and OGNL is not distributed as an OSGi bundle. In theory Apache Commons OGNL 4 should provide that in the future, but to be honest at this point I even doubt that Apache Commons OGNL 4 will ever exist. Not having an official OSGi module means that OSGi-enabled projects (like Apache Sling itself) use an OSGi bundle from Apache ServiceMix. This of course can create a dependency issue, as Apache ServiceMix does not have to provide a new version of the OGNL bundle immediately after a new version of OGNL is released, and it's not the first time we need immediate changes in OGNL itself to solve Thymeleaf scenarios –I've committed several modifications to OGNL myself–. Depending on a third-party (and potentially outdated) ServiceMix bundle is not an option IMO. Nor it is, of course, bundling OGNL itself inside the Thymeleaf core, which would be very invasive and provoke an important maintenance mess.

3. Spring Framework does not provide OSGi bundle metadata, nor they will in the future, apparently. This is a decision they explicity made some years ago.

4. Topics such as the future integration/interoperability of OSGi and Java 9's JPMS make this step IMHO more risky. If JPMS comes and interoperability with OSGi isn't direct, should we then add metadata for *two* different, incompatible module systems? Maintenability would most possibly suffer.

5. The amount of effort to be invested in properly-maintained OSGi metadata is significant, as your PR in my opinion shows. It's not that all those `package-info.java` files are large or complex in themselves when examined separately, but keeping all that versioning information up-to-date as changes are made to any packages (which is something that, obviously, happens constantly) would be non-trivial and very error-prone in an environment in which neither developers nor contributors are OSGi-educated. And past tests showed to us that automatic metadata generation by the Apache Felix Maven plugin has issues when processing Thymeleaf's code base.

6. Thymeleaf's two other dependencies besides OGNL, Unbescape and AttoParser (both of which I also authored) do provide OSGi metadata. I did this because these are small, dependency-free projects for which automatic metadata generation seems to work just fine. So this means the process for creating OSGi bundles for Thymeleaf outside the Thymeleaf project by those users who need them (or other projects in the likes of Apache ServiceMix) should be easier without the need for us at Thymeleaf to affect the maintainability of the core.


So I'm going to keep considering this a "wontfix" for now, and proceed to close this PR. I'm really sorry that this might mean an extra maintenance burden for your own projects, but unfortunately I'm convinced that the price to be paid for adding this at the Thymeleaf core, especially in what means for future maintainability, is too high.

**Pull request closed without merging**
