### PR TITLE
Update maven dependencies and plugins ->  BUILD SUCCESS (No tests availa...

### PR DESCRIPTION
**Pull request by good92**
...ble)

spock tests: http://code.google.com/p/spock/

### CODE REVIEW

**Comment by danielfernandez** [comment]
Sorry, do you mean that some tests are failing for you and by modifying these dependencies they work?

**Comment by good92** [comment]
No, I means that I have no access to the code test units: 
https://github.com/thymeleaf/thymeleaf/tree/2.1-master/src/test/java

**Comment by good92** [comment]
I found them, I will try to check it against
https://github.com/thymeleaf/thymeleaf-testing

**Comment by danielfernandez** [comment]
What do you mean with "have no access"? Can't you access the thymeleaf-tests repository? It should be public... http://github.com/thymeleaf/thymeleaf-tests

See http://www.thymeleaf.org/faq.html#testing for more info

**Comment by danielfernandez** [comment]
In order to apply your patch I need you to explicitly accept the Contribution Terms: https://github.com/thymeleaf/thymeleaf-dist/blob/master/CONTRIBUTING.markdown (a comment here will suffice).

Some maven plugin versions (gpg and releases, specifically) will not be upgradeable because their version was carefully chosen to avoid specific combinations of bugs appeared in newer versions. I will manually take those versions back after applying the patch, however.

**Comment by good92** [comment]
I am please to contribute and I accept the Contribution Terms: https://github.com/thymeleaf/thymeleaf-dist/blob/master/CONTRIBUTING.markdown.

Ok, no problem for the maven plugins.
In fact, I am not able to cover all your tests, it is just a happy contribution to push the things further in order to benefit from the libraries dependencies improvements (Springs Framework, ognl ...).

**Comment by danielfernandez** [comment]
Related to #211 javassist cannot be updated either. The remaining dependencies and maven plugins should be checked for Java 5 compatibility as well.

**Pull request merged**
