### PR TITLE
#471 - Add parsing for path segment identifier in path templates

### LINKED ISSUE #470: Path variable not correctly escaped in link
I'm using Thymeleaf (3.0.0.BETA02) in my Spring MVC app.

I'm trying to create a URL. The code looks like this:

`<a href="edit.html" th:href="@{/slugs/edit/{id}(id=${slug.id})}">[[${slug.id}]]</a>`

This works fine, except that the value of ${slug.id} might be something like slug:/path/to/page (the ID is used for storage in a Couchbase repository), and this value is NOT escaped. So I end up with a URL that looks like this: /slugs/edit/slug:/path/to/page

This then gives me a 404 because the URL doesn't map to a controller.

What I want is to have the URL created so that it's escaped:

/slugs/edit/slug%3A%2Fpath%2Fto%2Fpage

I can see that in the StandardLinkBuilder class, at line 344, the 'escapedReplacement' variable is defined and assigned to. This only gets run through 'UriEscape.escapeUriPath' when there is actually a question mark added at the end of the url string. If it's not there then 'start' is -1 and 'UriEscape.escapeUriPath' never gets executed.

The other issue (this may be by design, I'm not sure), but I think that the use of 'UriEscape.escapeUriPath' should be 'escapeUriPathSegment' instead.

### PR DESCRIPTION
**Pull request by jimmythomson**
Also fixes #470. This is my first PR so please feel free to let me know where I've gone wrong. I'll be adding a related PR on the tests project very shortly.

### CODE REVIEW

**Comment by jimmythomson** [comment]
I can confirm that I've read and accept the Contribution Terms and Conditions.

**Comment by danielfernandez** [comment]
Looks great, thanks. `3.0.0-SNAPSHOT` has been updated.

I would be happy to add you as a contributor here: http://www.thymeleaf.org/team.html, unless you prefer to opt-out. In order to do so, I would need a country (UK, I suppose) and a personal non-corporate email.

Also note that the format for that page is going to change in the very near future, as soon as we publish our new website (which should happen in a couple of weeks), and once changed we will be linking to your GitHub profile instead.

**Comment by jimmythomson** [comment]
Thanks, Daniel. Don't worry about adding me to the list. Perhaps if I contribute more in the future :)

**Comment by danielfernandez** [comment]
OK, as you prefer. You will be more than welcome to contribute more in the future :)

**Pull request merged**
